name: Test

on:
  pull_request:
    branches:
      - master

jobs:
  test-unit:
    name: Unit test
    runs-on: [ubuntu-latest]
    steps:
      - name: Set up Go 1.23
        uses: actions/setup-go@v4
        with:
          go-version: 1.23.1
          cache: false
      - name: Check-out code
        uses: actions/checkout@v4
      - name: Run unit tests
        run: make test-unit
